"""Public participant API for the deterministic fuel-node digital twin."""

from kosmohak.simulation.engine import simulate
from kosmohak.risk import (
    evaluate_mitigation,
    evaluate_risk,
    evaluate_risk_set,
    find_failure_threshold,
    sensitivity_sweep,
)
from kosmohak.optimization import (
    DecisionLocks,
    OptimizerConfig,
    explore_alternatives,
    improve_plan,
    improve_resilience,
    repair_plan,
)
from kosmohak.service import (
    UI_BACKEND_API_VERSION,
    ApplicationContext,
    ServiceError,
    ValidationResult,
    build_download_bundle,
    build_plan,
    compare_plans,
    evaluate_both_scenarios,
    evaluate_plan,
    load_application_context,
    load_plan,
    save_plan,
    to_service_error,
    validate_plan,
)
from kosmohak.workspace import (
    CaseWorkspace,
    FutureYearSpec,
    ResearchSourceSpec,
    add_research_source,
    extend_horizon,
)

__all__ = [
    "UI_BACKEND_API_VERSION",
    "ApplicationContext",
    "ServiceError",
    "ValidationResult",
    "load_application_context",
    "build_plan",
    "load_plan",
    "save_plan",
    "validate_plan",
    "build_download_bundle",
    "to_service_error",
    "simulate",
    "evaluate_risk",
    "evaluate_risk_set",
    "evaluate_mitigation",
    "sensitivity_sweep",
    "find_failure_threshold",
    "CaseWorkspace",
    "ResearchSourceSpec",
    "FutureYearSpec",
    "add_research_source",
    "extend_horizon",
    "evaluate_plan",
    "evaluate_both_scenarios",
    "compare_plans",
    "DecisionLocks",
    "OptimizerConfig",
    "repair_plan",
    "improve_plan",
    "improve_resilience",
    "explore_alternatives",
]
